#ifndef DN_CONFIG_H
#define DN_CONFIG_H

#define DN_DEBUG 1

#define DN_DEFAULT_HOST_NAME      "127.0.0.1"
#define DN_DEFAULT_PORT_NUMBER    8000U
#define DN_DEFAULT_MAX_PEER_COUNT 32U
#define DN_DEFAULT_SERVICE_DELAY  50U





#endif